Feature/custom fields import
zetkin/organize.zetk.in pull request #1121
Opened 2020-10-21 04:30 UTC by niklasva82

Implements UI for custom field import.

Resolves #1096

2020-10-21 04:37 UTC, niklasva82 commented
There is a problem with the select box that I haven't been able to track down. Everything seems to work properly otherwise, it's a cosmetic issue but pretty important from a users point of view.
To reproduce:
1. Select a file to import
2. In one of the columns, select a custom field

Expected result: The select box stays at that field.
Actual result: The select box jumps back to "Skip column", even though the state changes in the background and the import including validation still works.

2020-10-21 12:15 UTC, richardolsson requested changes
I know this is still a draft, but since we seem to miss each other during the days I thought I'd still do an initial review.

As far as I can tell, it seems to work as expected. But I think it's unnecessarily complex in some ways. One such way is JSON support, which I think we could do without (it's enough to support JSON through the API).

Another way is the `field_type` configuration attribute, which I think we should get rid off and instead let the back-end figure out the type based on `field_id`.

Let me know what you think!

2020-10-21 12:15 UTC, richardolsson commented on src/actions/importer.js
> +                    r[jsonIdx] = JSON.parse(value);
This is not dealing correctly with empty cells. I tried to find an easy solution (e.g. `!!value? JSON.parse(value) : null`) but I think that only introduces other issues, like how do we deal with accidental overwriting when cells are empty? There also seems to be some issues with how arrays are handled when sent off to the back-end.

My suggestion is that we don't support JSON fields at all in the importer. I.e. filter them out in `ImporterColumnHead` and remove the validation/parsing code.

2020-10-21 12:15 UTC, richardolsson commented on src/components/misc/importer/ImporterColumnHead.jsx
> +            obj['person_field.' + field.data.id + '.' + field.data.type] = field.data.title;
This seems unnecessarily complex. Maybe this is what's causing that bug you were experiencing? I'm guessing this is there to be able to send `field_type` along with the `config` but as I've mentioned elsewhere I don't think we should be including `field_type` there. Which should allow for simplifying this.

2020-10-21 12:24 UTC, richardolsson commented
On a separate note, I think we should put the _Custom Fields_ section right after the _Personal data fields_ section in the `<select>`, before the _Other data_ section. Custom fields and Person fields are closely related. Do you agree?

![image](https://user-images.githubusercontent.com/550212/96718774-c6763080-13a8-11eb-9128-c44fe474a164.png)

2020-10-22 01:29 UTC, niklasva82 commented
> On a separate note, I think we should put the _Custom Fields_ section right after the _Personal data fields_ section in the `<select>`, before the _Other data_ section. Custom fields and Person fields are closely related. Do you agree?
> 
> ![image](https://user-images.githubusercontent.com/550212/96718774-c6763080-13a8-11eb-9128-c44fe474a164.png)

Makes sense, fixed.

2020-10-22 08:11 UTC, richardolsson commented
Is this ready for review now? @niklasva82

2020-10-22 09:53 UTC, niklasva82 commented
Fixed the UI bug and it's now ready for review.

2020-10-22 12:43 UTC, richardolsson approved these changes
LGTM! 🎉

2020-10-22 12:43 UTC, merged