Enhancement/editable text limit
zetkin/organize.zetk.in pull request #1163
Opened 2020-11-17 17:14 UTC by kristofferlarberg

Resolves #1158. Adds limitation to EditableText via maxLength prop as well as limits possibility to make newlines via onKeyDown prop.

There is an issue with contenteditable adding a newline at the end of an entered text. This makes it possible to make one newline upon making changes to the previously added text. This is related to the fact that contenteditable accepts formatting onpaste (which is cleared onBlur).

2020-11-18 12:38 UTC, niklasva82 requested changes

2020-11-19 13:14 UTC, niklasva82 requested changes
Everything appears to work now! Great work!

There is a bit of a strange setting of state.text in onFocus though, which is not used anywhere else. This appears to do nothing and should probably be removed.

2020-11-19 13:23 UTC, kristofferlarberg commented
Great! Yes, I've been wondering about those lines. I'll remove them.

2020-11-22 18:25 UTC, niklasva82 approved these changes
Great work! You need to make this a regular PR rather than a draft PR for it to be merged!

2020-11-23 15:38 UTC, richardolsson commented
I would actually like to request that you create a new pull request which is more to the point, like we discussed previously with another PR. Or you could squash together commits into a few succinct commits. There is a lot of experimentation going on in this pull request, and it would be nice to keep the commit history a little bit cleaner post merging.

Are you ok with that @kristofferlarberg?

2020-11-24 09:37 UTC, kristofferlarberg commented
Of course, I'll try squashing the commits into two? 
1. onKeyDown maxlength and application of prop 
2. onKeyDown with prevEnter and application of prop

2020-11-24 11:41 UTC, richardolsson commented
> Of course, I'll try squashing the commits into two?
> 
> 1. onKeyDown maxlength and application of prop
> 2. onKeyDown with prevEnter and application of prop
> 
> Edit: Will make a new pull request instead.

Sounds good! The property for single-/multi-line should really be called something like just that. Probably `multiline={ true}`. Two reasons for this:

* In general it's a good idea to avoid "negative" properties
* The `preventEnter` name is an implementation detail. What happens if you paste several lines, i.e. insert newlines without pressing "enter". That should also be prevented.

Looking forward to a separate PR! Sorry for the hassle. 🙄

2020-11-24 11:41 UTC, closed without merging